export enum ScreenId {
  // Observe
  DASHBOARD = 'DASHBOARD',
  TELEMETRY = 'TELEMETRY',
  ANALYTICS = 'ANALYTICS',
  
  // Operate
  BATCHES_LIST = 'BATCHES_LIST',
  BATCHES_CREATE = 'BATCHES_CREATE',
  BATCHES_DETAIL = 'BATCHES_DETAIL',
  BATTERIES_LIST = 'BATTERIES_LIST',
  BATTERIES_DETAIL = 'BATTERIES_DETAIL',
  PROVISIONING = 'PROVISIONING', // The Console
  PROVISIONING_STATION_SETUP = 'PROVISIONING_STATION_SETUP', // Station Config
  INVENTORY = 'INVENTORY',
  DISPATCH = 'DISPATCH',
  
  // Assure
  EOL_QA_STATION = 'EOL_QA_STATION', // Station UI
  EOL_QA_STATION_SETUP = 'EOL_QA_STATION_SETUP',
  EOL_QA_REVIEW = 'EOL_QA_REVIEW',
  
  // Resolve
  WARRANTY = 'WARRANTY',
  
  // Govern
  COMPLIANCE = 'COMPLIANCE',
  CUSTODY = 'CUSTODY',
  
  // Admin
  SETTINGS = 'SETTINGS',
  RBAC_VIEW = 'RBAC_VIEW',
}

export const SCREEN_GROUPS = {
  OBSERVE: [ScreenId.DASHBOARD, ScreenId.TELEMETRY, ScreenId.ANALYTICS],
  OPERATE: [ScreenId.BATCHES_LIST, ScreenId.BATTERIES_LIST, ScreenId.PROVISIONING, ScreenId.PROVISIONING_STATION_SETUP, ScreenId.INVENTORY, ScreenId.DISPATCH],
  ASSURE: [ScreenId.EOL_QA_STATION, ScreenId.EOL_QA_STATION_SETUP, ScreenId.EOL_QA_REVIEW],
  RESOLVE: [ScreenId.WARRANTY],
  GOVERN: [ScreenId.COMPLIANCE, ScreenId.CUSTODY],
  ADMIN: [ScreenId.SETTINGS, ScreenId.RBAC_VIEW],
};