export enum ScreenId {
  // Observe
  DASHBOARD = 'DASHBOARD',
  DASHBOARD_EXEC_SUMMARY = 'DASHBOARD_EXEC_SUMMARY',
  DASHBOARD_PRODUCTION = 'DASHBOARD_PRODUCTION',
  DASHBOARD_QUALITY = 'DASHBOARD_QUALITY',
  DASHBOARD_LOGISTICS = 'DASHBOARD_LOGISTICS',
  DASHBOARD_RISK_COMPLIANCE = 'DASHBOARD_RISK_COMPLIANCE',

  TELEMETRY = 'TELEMETRY',
  TELEMETRY_LIVE_VIEW = 'TELEMETRY_LIVE_VIEW',
  TELEMETRY_HISTORY_VIEW = 'TELEMETRY_HISTORY_VIEW',
  TELEMETRY_EXPORT = 'TELEMETRY_EXPORT',

  ANALYTICS = 'ANALYTICS',
  ANALYTICS_OVERVIEW_TAB = 'ANALYTICS_OVERVIEW_TAB',
  ANALYTICS_BATCH_TAB = 'ANALYTICS_BATCH_TAB',
  ANALYTICS_STATION_TAB = 'ANALYTICS_STATION_TAB',
  ANALYTICS_QUALITY_TAB = 'ANALYTICS_QUALITY_TAB',
  ANALYTICS_LOCATION_TAB = 'ANALYTICS_LOCATION_TAB',
  ANALYTICS_REPORTS_TAB = 'ANALYTICS_REPORTS_TAB',
  ANALYTICS_EXPORT = 'ANALYTICS_EXPORT',
  
  // Operate
  BATCHES_LIST = 'BATCHES_LIST',
  BATCHES_CREATE = 'BATCHES_CREATE',
  BATCHES_DETAIL = 'BATCHES_DETAIL',
  BATTERIES_LIST = 'BATTERIES_LIST',
  BATTERIES_DETAIL = 'BATTERIES_DETAIL',
  PROVISIONING = 'PROVISIONING', // The Console
  PROVISIONING_STATION_SETUP = 'PROVISIONING_STATION_SETUP', // Station Config
  INVENTORY = 'INVENTORY',
  DISPATCH = 'DISPATCH', // Legacy group holder, kept for sidebar if needed, but specific screens below preferred
  DISPATCH_LIST = 'DISPATCH_LIST',
  DISPATCH_DETAIL = 'DISPATCH_DETAIL',
  
  // Assure
  EOL_QA_STATION = 'EOL_QA_STATION', // Station UI
  EOL_QA_STATION_SETUP = 'EOL_QA_STATION_SETUP',
  EOL_QA_REVIEW = 'EOL_QA_REVIEW',
  
  // Resolve
  WARRANTY = 'WARRANTY',
  
  // Govern
  COMPLIANCE = 'COMPLIANCE',
  CUSTODY = 'CUSTODY',
  
  // Admin
  SETTINGS = 'SETTINGS',
  RBAC_VIEW = 'RBAC_VIEW',
}

export const SCREEN_GROUPS = {
  OBSERVE: [ScreenId.DASHBOARD, ScreenId.TELEMETRY, ScreenId.ANALYTICS],
  OPERATE: [ScreenId.BATCHES_LIST, ScreenId.BATTERIES_LIST, ScreenId.PROVISIONING, ScreenId.PROVISIONING_STATION_SETUP, ScreenId.INVENTORY, ScreenId.DISPATCH_LIST],
  ASSURE: [ScreenId.EOL_QA_STATION, ScreenId.EOL_QA_STATION_SETUP, ScreenId.EOL_QA_REVIEW],
  RESOLVE: [ScreenId.WARRANTY],
  GOVERN: [ScreenId.COMPLIANCE, ScreenId.CUSTODY],
  ADMIN: [ScreenId.SETTINGS, ScreenId.RBAC_VIEW],
};